---
- name: Install xquartz (for Ricty)
  homebrew_cask: name=xquartz

- name: Install fontforge (for Ricty)
  homebrew: name=fontforge

- name: Install Ricty
  homebrew: name=ricty options=powerline,vim-powerline

- name: Copy font file
  shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
  args:
    creates: ~/Library/Fonts/Ricty-Bold.ttf
  notify: run fc-cache
